name: docker

#env_file:
#  - path: ./.env
#    required: true # default

#include :
#  - path: "core-apps/docker-compose.yml"
#  - path: "immich-app/docker-compose.yml"
#  - path: "pvr-apps/docker-compose.yml"